apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride | default .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride | default .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride | default .Release.Name }}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: {{ .Values.nameOverride | default .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--spring.profiles.active={{ .Values.springProfile }}"
          ports:
            - containerPort: {{ .Values.image.containerPort }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
