apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (printf "%s-service" .Release.Name) }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default .Release.Name }}
    app.kubernetes.io/instance: {{ .Values.nameOverride | default .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.nameOverride | default .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
